spring.application.name=shoppingkeep
# データベース（H2）の接続設定
spring.datasource.url=jdbc:h2:mem:shoppingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2の管理画面（コンソール）をブラウザで有効にする設定
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# アプリ起動時にJavaのクラスに合わせて自動でテーブルを作成・更新する
spring.jpa.hibernate.ddl-auto=update
# 実行されるSQLをコンソールに表示して確認できるようにする
spring.jpa.show-sql=true